/*
 * GuiAppFrameAdministration.java
 * 
 * Copyright (C) 2009 Nicola Roberto Viganò
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * GuiAppFrameAdministration.java
 *
 * Created on 21-mag-2009, 19.59.58
 */

package gestionecassa.clients.administration.gui;

import gestionecassa.clients.administration.AdminPrefs;
import gestionecassa.clients.gui.GuiAppFrame;
import gestionecassa.clients.gui.GuiHelper;
import gestionecassa.clients.gui.GuiOkCancelDialog;
import gestionecassa.clients.gui.GuiPreferencesPanel;
import gestionecassa.clients.administration.AdministrationAPI;

/**
 *
 * @author ben
 */
public class GuiAppFrameAdministration extends GuiAppFrame<AdministrationAPI> {

    /**
     * 
     */
    GuiStatusAdministrationPanel statusPanel;

    /**
     * Creates new form GuiAppFrameAdministration
     * @param baseClient reference to the client implementation
     */
    public GuiAppFrameAdministration(AdministrationAPI baseClient) {
        super(baseClient);
        initComponents();

        statusPanel = new GuiStatusAdministrationPanel();

        GuiHelper.MngBorderLayout.init(getContentPane());
        GuiHelper.MngBorderLayout.putTop(getContentPane(), toolbar);
        GuiHelper.MngBorderLayout.putCenter(getContentPane(), jScrollPanelMain);
        GuiHelper.MngBorderLayout.putRight(getContentPane(), statusPanel);

        enableLogout(false);

        GuiHelper.packAndCenter(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables

    /**
     * 
     */
    @Override
    public void selectedDialogOptions() {
        new GuiOkCancelDialog(this, "Client Options",
                  new GuiPreferencesPanel<AdminPrefs>(baseClient)).setVisible(true);
    }
}
