/*
 * GuiSingoloBeneOrdinePanel.java
 * 
 * Copyright (C) 2009 Nicola Roberto Viganò
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * GuiSingoloBeneOrdinePanel.java
 *
 * Created on 22-mag-2009, 12.36.51
 */

package gestionecassa.clients.cassa;

import gestionecassa.BeneVenduto;
import java.text.ParseException;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author ben
 */
public class GuiSingoloBeneOrdinePanel extends GuiAbstrSingoloBenePanel {

    BeneVenduto bene;

    SpinnerNumberModel spinnerModel;

    /**
     * Creates new form GuiSingoloBeneOrdinePanel
     *
     * @param nome
     */
    public GuiSingoloBeneOrdinePanel(BeneVenduto bene) {
        initComponents();
        this.bene = bene;

        spinnerModel = new SpinnerNumberModel(0, 0, 255, 1);
        jSpinnerNum.setModel(spinnerModel);

        jLabelNomeBene.setText(bene.getNome());
        jLabelPrezzo.setText("€ " + bene.getPrezzo());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabelNomeBene = new javax.swing.JLabel();
    jButtonMore = new javax.swing.JButton();
    jSpinnerNum = new javax.swing.JSpinner();
    jButtonLess = new javax.swing.JButton();
    jLabelPrezzo = new javax.swing.JLabel();

    setBorder(javax.swing.BorderFactory.createEtchedBorder());

    jLabelNomeBene.setText("Nome");

    jButtonMore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionecassa/resources/list-add.png"))); // NOI18N
    jButtonMore.setFocusable(false);
    jButtonMore.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButtonMore.setMaximumSize(new java.awt.Dimension(28, 34));
    jButtonMore.setMinimumSize(new java.awt.Dimension(24, 34));
    jButtonMore.setPreferredSize(new java.awt.Dimension(26, 34));
    jButtonMore.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jButtonMore.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonMoreActionPerformed(evt);
      }
    });

    jSpinnerNum.setMaximumSize(new java.awt.Dimension(48, 32767));

    jButtonLess.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionecassa/resources/list-remove.png"))); // NOI18N
    jButtonLess.setMaximumSize(new java.awt.Dimension(28, 34));
    jButtonLess.setMinimumSize(new java.awt.Dimension(24, 34));
    jButtonLess.setPreferredSize(new java.awt.Dimension(26, 34));
    jButtonLess.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonLessActionPerformed(evt);
      }
    });

    jLabelPrezzo.setText("Prezzo");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabelNomeBene)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
        .addComponent(jLabelPrezzo)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jButtonLess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jSpinnerNum, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jButtonMore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabelNomeBene)
          .addComponent(jButtonMore, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jSpinnerNum, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jButtonLess, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabelPrezzo))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

    /**
     *
     * @param evt
     */
    private void jButtonMoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMoreActionPerformed
        Object next = spinnerModel.getNextValue();
        if (next != null) {
            jSpinnerNum.setValue(next);
        }
}//GEN-LAST:event_jButtonMoreActionPerformed

    /**
     *
     * @param evt
     */
    private void jButtonLessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLessActionPerformed
        Object previous = spinnerModel.getPreviousValue();
        if (previous != null) {
            jSpinnerNum.setValue(previous);
        }
    }//GEN-LAST:event_jButtonLessActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButtonLess;
  private javax.swing.JButton jButtonMore;
  private javax.swing.JLabel jLabelNomeBene;
  private javax.swing.JLabel jLabelPrezzo;
  private javax.swing.JSpinner jSpinnerNum;
  // End of variables declaration//GEN-END:variables

    /**
     * 
     * @return
     */
    public int getJSpinnerNum() {
        try {
            jSpinnerNum.commitEdit();
        } catch (ParseException ex) {
            jSpinnerNum.setValue(spinnerModel.getValue());
        }
        return spinnerModel.getNumber().intValue();
    }

    /**
     * 
     */
    public void clean() {
        jSpinnerNum.setValue(spinnerModel.getMinimum());
    }

}
