/*
 * GuiAppFrameCassa.java
 * 
 * Copyright (C) 2009 Nicola Roberto Viganò
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * GuiAppFrameCassa.java
 *
 * Created on 21-mag-2009, 19.54.50
 */

package gestionecassa.clients.cassa.gui;

import gestionecassa.clients.ClientAPI;
import gestionecassa.clients.GuiAppFrame;
import gestionecassa.clients.GuiOptionsDialog;
import java.awt.BorderLayout;

/**
 *
 * @author ben
 */
public class GuiAppFrameCassa extends GuiAppFrame {

    /**
     *
     */
    GuiArticlesListDialog dialogListaBeni;

    /**
     *
     */
    GuiToolbarCassaPanel toolbar;

    /**
     * 
     */
    GuiStatusCassaPanel statusPanel;

    /**
     * Creates new form GuiAppFrameCassa
     *
     * @param owner
     */
    public GuiAppFrameCassa(ClientAPI owner) {
        super(owner);
        initComponents();

        toolbar = new GuiToolbarCassaPanel(this);

        jScrollPanelMain = new javax.swing.JScrollPane();

        statusPanel = new GuiStatusCassaPanel(owner.getHostname());

        if (!(getContentPane().getLayout() instanceof BorderLayout)) {
            getContentPane().setLayout(new BorderLayout());
        }
        
        getContentPane().add(toolbar, java.awt.BorderLayout.PAGE_START);
        getContentPane().add(jScrollPanelMain, java.awt.BorderLayout.CENTER);
        getContentPane().add(statusPanel, java.awt.BorderLayout.LINE_END);

        enableLogout(false);
        enableListaBeni(false);

        packAndCenter();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables


    /**
     * Enables or disables logout button.
     *
     * @param value
     */
    public void enableLogout(boolean value) {
        toolbar.enableLogout(value);
    }

    /**
     *
     */
    public void cleanDialogListaBeni() {
        dialogListaBeni = null;
    }

    /**
     *
     * @param value
     */
    public void enableListaBeni(boolean value) {
        toolbar.enableListaBeni(value);
        if (!value) {
            this.dialogListaBeni = null;
        }
    }

    /**
     *
     */
    void selectedDialogListaBeni() {
        if (dialogListaBeni == null) {
            dialogListaBeni = new GuiArticlesListDialog(this, false);
            dialogListaBeni.setListaBeni(owner.getListaBeni());
            dialogListaBeni.setVisible(true);
        } else {
            dialogListaBeni.setVisible(true);
            dialogListaBeni.requestFocus();
        }
    }

    /**
     * 
     */
    void selectedDialogOptions() {
        new GuiOptionsDialog(this, true, owner).setVisible(true);
    }

    /**
     *
     * @param username
     */
    public void updateUsernameStatus(String username) {
        statusPanel.setLogin(username);
    }

    /**
     * 
     */
    public void resetStatus() {
        statusPanel.reset();
    }

    /**
     *
     * @param price
     */
    void updateCurrentOrder(double price) {
        statusPanel.setCurrentOrder(price);
    }

    /**
     *
     * @param price
     */
    void updateNewOrder(double price) {
        statusPanel.setLastOrder(price);
    }

    /**
     * 
     */
    void cleanLastOrder() {
        statusPanel.cleanLastOrder();
    }
}
