/*
 * GuiAppFrameCassa.java
 * 
 * Copyright (C) 2009 Nicola Roberto Viganò
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * GuiAppFrameCassa.java
 *
 * Created on 21-mag-2009, 19.54.50
 */

package gestionecassa.clients.cassa.gui;

import gestionecassa.clients.gui.GuiAppFrame;
import gestionecassa.clients.gui.GuiHelper;
import gestionecassa.clients.gui.GuiOkCancelDialog;
import gestionecassa.clients.gui.GuiPreferencesPanel;
import gestionecassa.clients.cassa.CassaAPI;
import gestionecassa.clients.cassa.CassaPrefs;

/**
 *
 * @author ben
 */
public class GuiAppFrameCassa extends GuiAppFrame<CassaAPI> {

    /**
     * 
     */
    GuiStatusCassaPanel statusPanel;

    /**
     * Creates new form GuiAppFrameCassa
     *
     * @param baseClient
     */
    public GuiAppFrameCassa(CassaAPI baseClient) {
        super(baseClient);
        initComponents();

        statusPanel = new GuiStatusCassaPanel(baseClient.getHostname());

        GuiHelper.MngBorderLayout.init(getContentPane());
        GuiHelper.MngBorderLayout.putTop(getContentPane(), toolbar);
        GuiHelper.MngBorderLayout.putCenter(getContentPane(), jScrollPanelMain);
        GuiHelper.MngBorderLayout.putRight(getContentPane(), statusPanel);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables

    /**
     * 
     */
    @Override
    public void selectedDialogOptions() {
        new GuiOkCancelDialog(this, "Client Options",
                  new GuiPreferencesPanel<CassaPrefs>(baseClient)).setVisible(true);
    }

    /**
     * Sets up the gui after a successful login
     * @param username String containing the username of the logged user
     */
    @Override
    public void setupAfterLogin(String username) {
        super.setupAfterLogin(username);
        GuiNewOrderPanel orderPanel = new GuiNewOrderPanel(baseClient, this);
        this.setContentPanel(orderPanel);
        statusPanel.setOrderPanel(orderPanel);
        statusPanel.setLogin(username);
    }

    /**
     * Resets the components that are no longer legal in that state after logout
     */
    @Override
    public void setdownAfterLogout() {
        super.setdownAfterLogout();
        statusPanel.setOrderPanel(null);
        statusPanel.reset();
    }

    /**
     * 
     * @return
     */
    public GuiStatusCassaPanel getStatusPanel() {
        return statusPanel;
    }
}
