/*
 * GuiNewOrderPanel.java
 * 
 * Copyright (C) 2009 Nicola Roberto Viganò
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * GuiNewOrderPanel.java
 *
 * Created on 12-mag-2009, 22.16.39
 */

package gestionecassa.clients.cassa.gui;

import gestionecassa.clients.cassa.*;
import gestionecassa.ArticleWithOptions;
import gestionecassa.Article;
import gestionecassa.ArticlesList;
import gestionecassa.order.Order;
import gestionecassa.order.EntrySingleArticle;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.GroupLayout.ParallelGroup;
import javax.swing.GroupLayout.SequentialGroup;
import javax.swing.KeyStroke;

/**
 *
 * @author ben
 */
public class GuiNewOrderPanel extends javax.swing.JPanel {

    /**
     * Reference alla classe della business logic
     */
    CassaAPI owner;

    GuiAppFrameCassa parent;

    /**
     * Local Reference to the goods list.
     */
    ArticlesList articlesList;

    /**
     * Lista appoggio che per ogni article associa un panel
     */
    List<RecordPanelsOfArticles> articlesTable;

    KeyStroke moreKeys[];
    KeyStroke lessKeys[];

    /** 
     * Creates new form GuiNewOrderPanel
     *
     * @param owner
     */
    public GuiNewOrderPanel(CassaAPI owner, GuiAppFrameCassa parent) {
        initComponents();
        this.owner = owner;
        this.parent = parent;

        initKeysShortcuts();
        fetchArticlesList();
        buildContentsList();
        buildVisualList();

        this.setPreferredSize(new Dimension(800, 450));

        this.getInputMap(WHEN_IN_FOCUSED_WINDOW).put(
                KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "ENTER");
        this.getActionMap().put("ENTER", new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                confirmAndSendNewOrder();
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanelArticlesList = new javax.swing.JPanel();

    setMinimumSize(new java.awt.Dimension(150, 150));

    javax.swing.GroupLayout jPanelArticlesListLayout = new javax.swing.GroupLayout(jPanelArticlesList);
    jPanelArticlesList.setLayout(jPanelArticlesListLayout);
    jPanelArticlesListLayout.setHorizontalGroup(
      jPanelArticlesListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 559, Short.MAX_VALUE)
    );
    jPanelArticlesListLayout.setVerticalGroup(
      jPanelArticlesListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 443, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanelArticlesList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanelArticlesList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel jPanelArticlesList;
  // End of variables declaration//GEN-END:variables

    /**
     * It assigns the keys for fast selection of chosen articles in this panel
     */
    private void initKeysShortcuts() {
        moreKeys = new KeyStroke[10];
        lessKeys = new KeyStroke[10];

        moreKeys[0] = KeyStroke.getKeyStroke(KeyEvent.VK_1,0);
        moreKeys[1] = KeyStroke.getKeyStroke(KeyEvent.VK_2,0);
        moreKeys[2] = KeyStroke.getKeyStroke(KeyEvent.VK_3,0);
        moreKeys[3] = KeyStroke.getKeyStroke(KeyEvent.VK_4,0);
        moreKeys[4] = KeyStroke.getKeyStroke(KeyEvent.VK_5,0);
        moreKeys[5] = KeyStroke.getKeyStroke(KeyEvent.VK_6,0);
        moreKeys[6] = KeyStroke.getKeyStroke(KeyEvent.VK_7,0);
        moreKeys[7] = KeyStroke.getKeyStroke(KeyEvent.VK_8,0);
        moreKeys[8] = KeyStroke.getKeyStroke(KeyEvent.VK_9,0);
        moreKeys[9] = KeyStroke.getKeyStroke(KeyEvent.VK_0,0);

        lessKeys[0] = KeyStroke.getKeyStroke(KeyEvent.VK_Q,0);
        lessKeys[1] = KeyStroke.getKeyStroke(KeyEvent.VK_W,0);
        lessKeys[2] = KeyStroke.getKeyStroke(KeyEvent.VK_E,0);
        lessKeys[3] = KeyStroke.getKeyStroke(KeyEvent.VK_R,0);
        lessKeys[4] = KeyStroke.getKeyStroke(KeyEvent.VK_T,0);
        lessKeys[5] = KeyStroke.getKeyStroke(KeyEvent.VK_Y,0);
        lessKeys[6] = KeyStroke.getKeyStroke(KeyEvent.VK_U,0);
        lessKeys[7] = KeyStroke.getKeyStroke(KeyEvent.VK_I,0);
        lessKeys[8] = KeyStroke.getKeyStroke(KeyEvent.VK_O,0);
        lessKeys[9] = KeyStroke.getKeyStroke(KeyEvent.VK_P,0);
    }

    /**
     * Popolates the list of the panels related to each article sold.
     */
    private void buildContentsList() {
        articlesTable = new ArrayList<RecordPanelsOfArticles>();
        int i = 0;
        for (Article bene : articlesList.getList()) {
            GuiAbstrSingleArticlePanel tempPanel;
            if (bene instanceof ArticleWithOptions) {
                tempPanel = 
                        new GuiOrderSingleArticleWOptionsPanel(this,
                                                    (ArticleWithOptions)bene,i);
            } else {
                tempPanel = new GuiOrderSingleArticlePanel(this,bene,i);
            }
            articlesTable.add(new RecordPanelsOfArticles(bene, tempPanel));
            i++;
        }
    }

    /**
     * It actually displays what the method <code>buildContentsList()</code>
     * stored in the table of SoldArticle-"Panel showing it".
     */
    private void buildVisualList() {

        /* Prima di tutto rimuoviamo i pannelli di prima che se no incasinano
         * tutto
         */
        jPanelArticlesList.removeAll();

        /* Creo il nuovo layout in cui organizzerò i nuovi pannelli
         */
        javax.swing.GroupLayout layout =
                new javax.swing.GroupLayout(jPanelArticlesList);
        jPanelArticlesList.setLayout(layout);

        /* Creo i due gruppi con cui organizzare i pannelli
         */
        ParallelGroup tempHorizGroup = layout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING);
        SequentialGroup tempSequGroup = layout.createSequentialGroup()
            .addContainerGap();

        /* Ciclo in cui aggiungo i pannelli ai gruppi con le impostazioni giuste
         */
        for (RecordPanelsOfArticles singoloRecord : articlesTable) {

            tempHorizGroup.addComponent(singoloRecord.panel,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE);

            tempSequGroup
                .addComponent(singoloRecord.panel,
                    javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(
                    javax.swing.LayoutStyle.ComponentPlacement.RELATED);
        }
        
        /* Ultimo spazio del gruppo verticale
         */
        tempSequGroup.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                      Short.MAX_VALUE);

        /* infine aggiungiamo il gruppo di elementi al layout della pagina
         * principale.
         */
        layout.setHorizontalGroup(
          layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tempHorizGroup)
                .addContainerGap() )
        );
        layout.setVerticalGroup(
          layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tempSequGroup)
        );
    }

    /**
     * Gets the ArticleList and stores it locally.
     */
    private void fetchArticlesList() {
        articlesList = owner.getArticlesList();
    }

    /**
     * it fetches the ArticleList from the server (through the CassaAPI)
     * and makes the client store it locally
     */
    void forceRMIRequestArticlesList() {
        try {
            owner.getRMIArticlesList();
        } catch (RemoteException ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Il server non ha risposto alla richiesta della lista",
                "Errore di comunicazione",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * If the new order is not empty, it sends it to the server and cleans the
     * gui, ready for compiling a new order.
     */
    void confirmAndSendNewOrder() {
        try {
            Order nuovoOrdine = createNewOrder();
            if (nuovoOrdine.getTotalPrice() != 0) {
                owner.sendRMINewOrder(nuovoOrdine);
                parent.updateNewOrder(computeOrderPrice(nuovoOrdine));
                this.cleanDataFields();
            }
        } catch (RemoteException ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Il server non ha risposto alla richiesta dell'invio del " +
                "nuovo ordine",
                "Errore di comunicazione",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Il server ha avuto problemi col DB",
                "Errore del Backend sul server",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Cleans the gui.
     */
    void cleanDataFields() {
        for (RecordPanelsOfArticles singoloRecord : articlesTable) {
            singoloRecord.panel.clean();
        }
        parent.updateCurrentOrder(0);
    }

    void updateList() {
        forceRMIRequestArticlesList();
        fetchArticlesList();
        buildContentsList();
        buildVisualList();
    }

    /**
     * Inner class that defines a record of the table of goods.
     *
     * @author ben
     */
    class RecordPanelsOfArticles {

        /**
         *
         */
        final Article article;

        /**
         *
         */
        final GuiAbstrSingleArticlePanel panel;

        /**
         * Explicit constructor
         *
         * @param article
         * @param panel
         */
        public RecordPanelsOfArticles(Article art,
                                      GuiAbstrSingleArticlePanel pan) {
            this.article = art;
            this.panel = pan;
        }
    }

    /**
     * Creates a new order from the chosen Articles
     *
     * @return the created order
     * 
     * @throws RemoteException
     */
    private Order createNewOrder() throws RemoteException {
        int tempNumTot = 0;
        Order tempOrd = new Order(owner.getUsername(), owner.getHostname());

        for (RecordPanelsOfArticles singoloRecord : articlesTable) {

            tempNumTot = singoloRecord.panel.getNumTot();

            if (singoloRecord.panel.getNumTot() != 0) {

                if (singoloRecord.article.hasOptions()) {

                    int progressive = owner.getNProgressivo(
                            singoloRecord.article.getName(), tempNumTot);
                    tempOrd.addArticleWithOptions(
                            (ArticleWithOptions)singoloRecord.article,
                            tempNumTot, progressive,
                            ((GuiOrderSingleArticleWOptionsPanel)
                                (singoloRecord.panel)).getListaParziali());
                } else {
                    tempOrd.addArticle(singoloRecord.article,tempNumTot);
                }
            }
        }
        tempOrd.setTotalPrice(computeOrderPrice(tempOrd));
        return tempOrd;
    }

    /**
     * It calculates the amount the "still to be committed" order will cost
     *
     * @return
     */
    private double computeCurrentOrder() {
        double output = 0;
        for (RecordPanelsOfArticles singoloRecord : articlesTable) {
            if (singoloRecord.panel.getNumTot() != 0) {
                output += singoloRecord.panel.getNumTot() *
                        singoloRecord.article.getPrice();
            }
        }
        return output;
    }

    /**
     * Committs the calculated price of the current partial order to the gui.
     */
    void updateCurrentOrder() {
        parent.updateCurrentOrder(computeCurrentOrder());
    }

    /**
     * Calculate price o the given Order
     *
     * @param ordine the order to calculate
     *
     * @return Price calculated.
     */
    private double computeOrderPrice(Order ordine) {
        List<EntrySingleArticle> lista = ordine.getArticlesSold();
        double output = 0;
        for (EntrySingleArticle singoloBene : lista) {
            output += singoloBene.numTot * singoloBene.article.getPrice();
        }
        return output;
    }

    /**
     * This cancells the last commited order. It's a function to treat carefully
     */
    void undoLastOrder() {
        final int result = javax.swing.JOptionPane.showConfirmDialog(this,
                "Vuoi veramente annullare l'ultimo ordine emesso?",
                "Annulla ultimo Ordine", javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.WARNING_MESSAGE);
        if (result == javax.swing.JOptionPane.YES_OPTION) {
            try {
                owner.delRMILastOrder();
                parent.cleanLastOrder();
                javax.swing.JOptionPane.showMessageDialog(this,
                    "L'ultimo Ordine emesso è stato annullato",
                    "Operazione terminata",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } catch (RemoteException ex) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Il server non ha risposto alla richiesta di annullamento",
                    "Errore di comunicazione",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            } catch (IOException ex) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Il server ha avuto problemi col DB",
                    "Errore del Backend sul server",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }
}
