/*
 * GuiOrderSingleOptionPanel.java
 * 
 * Copyright (C) 2009 Nicola Roberto Viganò
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * GuiOrderSingleOptionPanel.java
 *
 * Created on 23-mag-2009, 14.11.41
 */

package gestionecassa.clients.cassa.gui;

import java.text.ParseException;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author ben
 */
public class GuiOrderSingleOptionPanel extends javax.swing.JPanel {

    /**
     *
     */
    GuiOrderSingleArticleWOptionsPanel parent;

    /**
     *
     */
    DefaultComboBoxModel comboModel;

    /**
     *
     */
    SpinnerNumberModel spinnerModel;

    /**
     * Creates new form GuiOrderSingleOptionPanel
     *
     * @param parent
     * @param opzioni
     */
    public GuiOrderSingleOptionPanel(GuiOrderSingleArticleWOptionsPanel parent,
            List<String> opzioni) {
        initComponents();
        this.parent = parent;

        spinnerModel = new SpinnerNumberModel(0, 0, 255, 1);
        jSpinnerNum.setModel(spinnerModel);

        comboModel = new DefaultComboBoxModel(opzioni.toArray());
        jComboBoxOpzione.setModel(comboModel);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jButtonRimuovi = new javax.swing.JButton();
    jButtonLess = new javax.swing.JButton();
    jSpinnerNum = new javax.swing.JSpinner();
    jButtonMore = new javax.swing.JButton();
    jComboBoxOpzione = new javax.swing.JComboBox();

    jButtonRimuovi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionecassa/resources/dialog-no.png"))); // NOI18N
    jButtonRimuovi.setText("Rimuovi");
    jButtonRimuovi.setPreferredSize(new java.awt.Dimension(113, 25));
    jButtonRimuovi.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonRimuoviActionPerformed(evt);
      }
    });

    jButtonLess.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionecassa/resources/list-remove.png"))); // NOI18N
    jButtonLess.setMaximumSize(new java.awt.Dimension(28, 25));
    jButtonLess.setMinimumSize(new java.awt.Dimension(24, 25));
    jButtonLess.setPreferredSize(new java.awt.Dimension(26, 25));
    jButtonLess.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonLessActionPerformed(evt);
      }
    });

    jSpinnerNum.setMaximumSize(new java.awt.Dimension(48, 32767));
    jSpinnerNum.setPreferredSize(new java.awt.Dimension(28, 25));

    jButtonMore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionecassa/resources/list-add.png"))); // NOI18N
    jButtonMore.setFocusable(false);
    jButtonMore.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButtonMore.setMaximumSize(new java.awt.Dimension(28, 25));
    jButtonMore.setMinimumSize(new java.awt.Dimension(24, 25));
    jButtonMore.setPreferredSize(new java.awt.Dimension(26, 25));
    jButtonMore.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jButtonMore.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonMoreActionPerformed(evt);
      }
    });

    jComboBoxOpzione.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jButtonRimuovi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
        .addComponent(jComboBoxOpzione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(12, 12, 12)
        .addComponent(jButtonLess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jSpinnerNum, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jButtonMore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
        .addComponent(jButtonRimuovi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addComponent(jComboBoxOpzione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
        .addComponent(jButtonMore, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addComponent(jSpinnerNum, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
      .addComponent(jButtonLess, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
  }// </editor-fold>//GEN-END:initComponents

    /**
     * 
     * @param evt
     */
    private void jButtonLessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLessActionPerformed
        less();
}//GEN-LAST:event_jButtonLessActionPerformed

    /**
     *
     * @param evt
     */
    private void jButtonMoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMoreActionPerformed
        more();
}//GEN-LAST:event_jButtonMoreActionPerformed

    /**
     *
     * @param evt
     */
    private void jButtonRimuoviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRimuoviActionPerformed
        parent.removeOptionPanel(this);
    }//GEN-LAST:event_jButtonRimuoviActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButtonLess;
  private javax.swing.JButton jButtonMore;
  private javax.swing.JButton jButtonRimuovi;
  private javax.swing.JComboBox jComboBoxOpzione;
  private javax.swing.JSpinner jSpinnerNum;
  // End of variables declaration//GEN-END:variables

    /**
     * Gets the partial count of items for the selected option
     *
     * @return
     */
    public int getNumParziale() {
        try {
            jSpinnerNum.commitEdit();
        } catch (ParseException ex) {
            jSpinnerNum.setValue(spinnerModel.getValue());
        }
        return spinnerModel.getNumber().intValue();
    }

    /**
     * Getter for the selected item in combo box
     *
     * @return The selected Option
     */
    public String getComboChoice() {
        return (String)comboModel.getSelectedItem();
    }

    /**
     * Gets the index of the selected item in the combobox
     *
     * @return the index
     */
    public int getComboNum() {
        return comboModel.getIndexOf(comboModel.getSelectedItem());
    }

    /**
     * 
     */
    void more() {
        Object next = spinnerModel.getNextValue();
        if (next != null) {
            jSpinnerNum.setValue(next);
        }
        parent.triggerUpdateCurrentOrder();
    }

    /**
     * 
     */
    void less() {
        Object previous = spinnerModel.getPreviousValue();
        if (previous != null) {
            jSpinnerNum.setValue(previous);
        }
        parent.triggerUpdateCurrentOrder();
    }
}
