/*
 * GuiOrderSingleArticlePanel.java
 * 
 * Copyright (C) 2009 Nicola Roberto Viganò
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * GuiOrderSingleArticlePanel.java
 *
 * Created on 22-mag-2009, 12.36.51
 */

package gestionecassa.clients.cassa.gui;

import gestionecassa.Article;
import java.awt.event.ActionEvent;
import java.text.ParseException;
import javax.swing.AbstractAction;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author ben
 */
public class GuiOrderSingleArticlePanel extends GuiAbstrSingleArticlePanel {

    Article article;

    SpinnerNumberModel spinnerModel;

    GuiNewOrderPanel parent;

    /**
     * Creates new form GuiOrderSingleArticlePanel
     *
     * @param nome
     */
    public GuiOrderSingleArticlePanel(GuiNewOrderPanel parent, Article bene, int i) {
        initComponents();
        this.article = bene;
        this.parent = parent;

        spinnerModel = new SpinnerNumberModel(0, 0, 255, 1);
        jSpinnerNum.setModel(spinnerModel);

        jLabelNameArticle.setText(bene.getName());
        jLabelPrice.setText("€ " + bene.getPrice());

        if (i < 10) {
            jButtonMore.getInputMap(WHEN_IN_FOCUSED_WINDOW).put(
                    Shortcuts.moreKeys[i], "MORE"+i);
            jButtonMore.getActionMap().put("MORE"+i, new AbstractAction() {
                public void actionPerformed(ActionEvent e) { more(); }
            });
            jButtonLess.getInputMap(WHEN_IN_FOCUSED_WINDOW).put(
                    Shortcuts.lessKeys[i], "LESS"+i);
            jButtonLess.getActionMap().put("LESS"+i, new AbstractAction() {
                public void actionPerformed(ActionEvent e) { less(); }
            });
        }

        jLabelNum.setText((i + 1) + ".");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabelNameArticle = new javax.swing.JLabel();
    jButtonMore = new javax.swing.JButton();
    jSpinnerNum = new javax.swing.JSpinner();
    jButtonLess = new javax.swing.JButton();
    jLabelPrice = new javax.swing.JLabel();
    jLabelNum = new javax.swing.JLabel();

    setBorder(javax.swing.BorderFactory.createEtchedBorder());

    jLabelNameArticle.setText("Nome");

    jButtonMore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionecassa/resources/list-add.png"))); // NOI18N
    jButtonMore.setFocusable(false);
    jButtonMore.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButtonMore.setMaximumSize(new java.awt.Dimension(28, 34));
    jButtonMore.setMinimumSize(new java.awt.Dimension(24, 34));
    jButtonMore.setPreferredSize(new java.awt.Dimension(26, 34));
    jButtonMore.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jButtonMore.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonMoreActionPerformed(evt);
      }
    });

    jSpinnerNum.setMaximumSize(new java.awt.Dimension(48, 32767));

    jButtonLess.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionecassa/resources/list-remove.png"))); // NOI18N
    jButtonLess.setMaximumSize(new java.awt.Dimension(28, 34));
    jButtonLess.setMinimumSize(new java.awt.Dimension(24, 34));
    jButtonLess.setPreferredSize(new java.awt.Dimension(26, 34));
    jButtonLess.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonLessActionPerformed(evt);
      }
    });

    jLabelPrice.setText("Prezzo");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabelNum)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabelNameArticle)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
        .addComponent(jLabelPrice)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jButtonLess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jSpinnerNum, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jButtonMore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabelNameArticle)
          .addComponent(jButtonMore, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jSpinnerNum, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jButtonLess, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabelPrice)
          .addComponent(jLabelNum))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

    /**
     *
     * @param evt
     */
    private void jButtonMoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMoreActionPerformed
        more();
}//GEN-LAST:event_jButtonMoreActionPerformed

    /**
     *
     * @param evt
     */
    private void jButtonLessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLessActionPerformed
        less();
    }//GEN-LAST:event_jButtonLessActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButtonLess;
  private javax.swing.JButton jButtonMore;
  private javax.swing.JLabel jLabelNameArticle;
  private javax.swing.JLabel jLabelNum;
  private javax.swing.JLabel jLabelPrice;
  private javax.swing.JSpinner jSpinnerNum;
  // End of variables declaration//GEN-END:variables

    /**
     * 
     * @return
     */
    public int getNumTot() {
        try {
            jSpinnerNum.commitEdit();
        } catch (ParseException ex) {
            jSpinnerNum.setValue(spinnerModel.getValue());
        }
        return spinnerModel.getNumber().intValue();
    }

    /**
     * 
     */
    @Override
    public void clean() {
        jSpinnerNum.setValue(spinnerModel.getMinimum());
    }

    public void more() {
        Object next = spinnerModel.getNextValue();
        if (next != null) {
            jSpinnerNum.setValue(next);
        }
        parent.updateCurrentOrder();
    }

    public void less() {
        Object previous = spinnerModel.getPreviousValue();
        if (previous != null) {
            jSpinnerNum.setValue(previous);
        }
        parent.updateCurrentOrder();
    }
}
