/*
 * GuiToolbarCassaPanel.java
 * 
 * Copyright (C) 2009 Nicola Roberto Viganò
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * GuiToolbarCassaPanel.java
 *
 * Created on 6-lug-2009, 15.46.33
 */

package gestionecassa.clients.cassa.gui;

/**
 *
 * @author ben
 */
public class GuiToolbarCassaPanel extends javax.swing.JPanel {

    GuiAppFrameCassa owner;

    /** Creates new form GuiToolbarCassaPanel */
    public GuiToolbarCassaPanel(GuiAppFrameCassa owner) {
        initComponents();
        this.owner = owner;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jToolBarMain = new javax.swing.JToolBar();
    jButtonLogout = new javax.swing.JButton();
    jSeparator1 = new javax.swing.JToolBar.Separator();
    jButtonList = new javax.swing.JButton();
    jSeparator2 = new javax.swing.JToolBar.Separator();
    jButtonOptions = new javax.swing.JButton();

    jToolBarMain.setFloatable(false);
    jToolBarMain.setRollover(true);

    jButtonLogout.setText("Logout");
    jButtonLogout.setFocusable(false);
    jButtonLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButtonLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonLogoutActionPerformed(evt);
      }
    });
    jToolBarMain.add(jButtonLogout);
    jToolBarMain.add(jSeparator1);

    jButtonList.setText("Lista beni venduti");
    jButtonList.setFocusable(false);
    jButtonList.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButtonList.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jButtonList.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonListActionPerformed(evt);
      }
    });
    jToolBarMain.add(jButtonList);
    jToolBarMain.add(jSeparator2);

    jButtonOptions.setText("Opzioni");
    jButtonOptions.setFocusable(false);
    jButtonOptions.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButtonOptions.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jButtonOptions.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonOptionsActionPerformed(evt);
      }
    });
    jToolBarMain.add(jButtonOptions);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jToolBarMain, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jToolBarMain, javax.swing.GroupLayout.PREFERRED_SIZE, 25, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        owner.logout();
}//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jButtonListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListActionPerformed
        owner.selectedDialogListaBeni();
}//GEN-LAST:event_jButtonListActionPerformed

    private void jButtonOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOptionsActionPerformed
        owner.selectedDialogOptions();
}//GEN-LAST:event_jButtonOptionsActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  protected javax.swing.JButton jButtonList;
  protected javax.swing.JButton jButtonLogout;
  protected javax.swing.JButton jButtonOptions;
  protected javax.swing.JToolBar.Separator jSeparator1;
  protected javax.swing.JToolBar.Separator jSeparator2;
  protected javax.swing.JToolBar jToolBarMain;
  // End of variables declaration//GEN-END:variables


    public void enableListaBeni(boolean value) {
        jButtonList.setEnabled(value);
    }
    
    /**
     * Enables or disables logout button.
     *
     * @param value
     */
    public void enableLogout(boolean value) {
        jButtonLogout.setEnabled(value);
    }
}
