/*
 * GuiVariableListPanel.java
 * 
 * Copyright (C) 2009 Nicola Roberto Viganò
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * GuiVariableListPanel.java
 *
 * Created on 4-set-2009, 18.18.59
 */

package gestionecassa.clients.cassa.gui;

import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.GroupLayout.ParallelGroup;
import javax.swing.GroupLayout.SequentialGroup;
import javax.swing.JPanel;
import javax.swing.KeyStroke;

/**
 *
 * @author ben
 */
abstract public class GuiVariableListPanel extends javax.swing.JPanel {

    /**
     * List that associates a panel to each article
     */
    protected List<RecordPanels> panelsTable;

    protected KeyStroke moreKeys[];
    protected KeyStroke lessKeys[];

    /** Creates new form GuiVariableListPanel */
    public GuiVariableListPanel() {
        initComponents();
        
        initKeysShortcuts();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 400, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 300, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables

    /**
     * It assigns the keys for fast selection of chosen articles in this displayedPanel
     */
    protected void initKeysShortcuts() {
        moreKeys = new KeyStroke[10];
        lessKeys = new KeyStroke[10];

        moreKeys[0] = KeyStroke.getKeyStroke(KeyEvent.VK_1,0);
        moreKeys[1] = KeyStroke.getKeyStroke(KeyEvent.VK_2,0);
        moreKeys[2] = KeyStroke.getKeyStroke(KeyEvent.VK_3,0);
        moreKeys[3] = KeyStroke.getKeyStroke(KeyEvent.VK_4,0);
        moreKeys[4] = KeyStroke.getKeyStroke(KeyEvent.VK_5,0);
        moreKeys[5] = KeyStroke.getKeyStroke(KeyEvent.VK_6,0);
        moreKeys[6] = KeyStroke.getKeyStroke(KeyEvent.VK_7,0);
        moreKeys[7] = KeyStroke.getKeyStroke(KeyEvent.VK_8,0);
        moreKeys[8] = KeyStroke.getKeyStroke(KeyEvent.VK_9,0);
        moreKeys[9] = KeyStroke.getKeyStroke(KeyEvent.VK_0,0);

        lessKeys[0] = KeyStroke.getKeyStroke(KeyEvent.VK_Q,0);
        lessKeys[1] = KeyStroke.getKeyStroke(KeyEvent.VK_W,0);
        lessKeys[2] = KeyStroke.getKeyStroke(KeyEvent.VK_E,0);
        lessKeys[3] = KeyStroke.getKeyStroke(KeyEvent.VK_R,0);
        lessKeys[4] = KeyStroke.getKeyStroke(KeyEvent.VK_T,0);
        lessKeys[5] = KeyStroke.getKeyStroke(KeyEvent.VK_Y,0);
        lessKeys[6] = KeyStroke.getKeyStroke(KeyEvent.VK_U,0);
        lessKeys[7] = KeyStroke.getKeyStroke(KeyEvent.VK_I,0);
        lessKeys[8] = KeyStroke.getKeyStroke(KeyEvent.VK_O,0);
        lessKeys[9] = KeyStroke.getKeyStroke(KeyEvent.VK_P,0);
    }

    /**
     * Popolates the list of the panels related to each article sold.
     */
    abstract protected void buildContentsList();

    /**
     * It actually displays what the method <code>buildContentsList()</code>
     * stored in the table of SoldArticle-"Panel showing it".
     */
    protected void buildVisualList() {

        /* Prima di tutto rimuoviamo i pannelli di prima che se no incasinano
         * tutto
         */
        this.removeAll();

        /* Creo il nuovo layout in cui organizzerò i nuovi pannelli
         */
        javax.swing.GroupLayout layout =
                new javax.swing.GroupLayout(this);
        this.setLayout(layout);

        /* Creo i due gruppi con cui organizzare i pannelli
         */
        ParallelGroup tempHorizGroup = layout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING);
        SequentialGroup tempSequGroup = layout.createSequentialGroup()
            .addContainerGap();

        /* Ciclo in cui aggiungo i pannelli ai gruppi con le impostazioni giuste
         */
        for (RecordPanels singleRecord : panelsTable) {

            tempHorizGroup.addComponent(singleRecord.displayedPanel,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE);

            tempSequGroup
                .addComponent(singleRecord.displayedPanel,
                    javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(
                    javax.swing.LayoutStyle.ComponentPlacement.RELATED);
        }

        /* Ultimo spazio del gruppo verticale
         */
        tempSequGroup.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                      Short.MAX_VALUE);

        /* infine aggiungiamo il gruppo di elementi al layout della pagina
         * principale.
         */
        layout.setHorizontalGroup(
          layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tempHorizGroup)
                .addContainerGap() )
        );
        layout.setVerticalGroup(
          layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tempSequGroup)
        );
    }

    /**
     * Cleans the gui.
     */
    void cleanDataFields() {
        for (RecordPanels singoloRecord : panelsTable) {
            singoloRecord.displayedPanel.clean();
        }
    }

    /**
     * Inner class that defines a record of panels and other useful info.
     *
     * @author ben
     */
    protected class RecordPanels {

        /**
         *
         */
        final GuiAbstrSingleArticlePanel displayedPanel;

        /**
         * Explicit constructor
         *
         * @param article
         * @param displayedPanel
         */
        public RecordPanels(GuiAbstrSingleArticlePanel pan) {
            this.displayedPanel = pan;
        }
    }
}
