/*
 * GuiAppFrameAmministrazione.java
 * 
 * Copyright (C) 2009 Nicola Roberto Viganò
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * GuiAppFrameAmministrazione.java
 *
 * Created on 21-mag-2009, 19.59.58
 */

package gestionecassa.clients.amministrazione;

import gestionecassa.clients.ClientAPI;
import gestionecassa.clients.GuiAppFrame;
import javax.swing.JPanel;

/**
 *
 * @author ben
 */
public class GuiAppFrameAmministrazione extends GuiAppFrame {

    /** Creates new form GuiAppFrameAmministrazione */
    public GuiAppFrameAmministrazione(ClientAPI owner) {
        super(owner);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jToolBarMain = new javax.swing.JToolBar();
    jButtonLogout = new javax.swing.JButton();
    jSeparator1 = new javax.swing.JToolBar.Separator();
    jButtonOptions = new javax.swing.JButton();
    jScrollPanelMain = new javax.swing.JScrollPane();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jToolBarMain.setFloatable(false);
    jToolBarMain.setRollover(true);

    jButtonLogout.setText("Logout");
    jButtonLogout.setFocusable(false);
    jButtonLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButtonLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonLogoutActionPerformed(evt);
      }
    });
    jToolBarMain.add(jButtonLogout);
    jToolBarMain.add(jSeparator1);

    jButtonOptions.setText("Opzioni");
    jButtonOptions.setFocusable(false);
    jButtonOptions.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButtonOptions.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jButtonOptions.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonOptionsActionPerformed(evt);
      }
    });
    jToolBarMain.add(jButtonOptions);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jToolBarMain, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
      .addComponent(jScrollPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jToolBarMain, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        logout();
}//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jButtonOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOptionsActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jButtonOptionsActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  protected javax.swing.JButton jButtonLogout;
  protected javax.swing.JButton jButtonOptions;
  protected javax.swing.JScrollPane jScrollPanelMain;
  protected javax.swing.JToolBar.Separator jSeparator1;
  protected javax.swing.JToolBar jToolBarMain;
  // End of variables declaration//GEN-END:variables

    /**
     * Enables or disables logout button.
     *
     * @param value
     */
    public void enableLogout(boolean value) {
        jButtonLogout.setEnabled(value);
    }

    /**
     * Sets the new panel into the work area
     *
     * @param content
     */
    public void setContentPanel(JPanel content) {
        jScrollPanelMain.setViewportView(content);
        this.pack();
    }

    /**
     * cleans the work area.
     */
    public void cleanContentPanel() {
        jScrollPanelMain.setViewportView(new JPanel());
    }
}
